### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by greatbiggiantbrain** [lokanchung/LaunchpadXFirmware#1]
I've been asking for no vegas mode on their support for a couple of years now.  Thanks for doing this!  
It's hard to blindly trust binaries unless one can audit the source.  Could you please provide the source?

**Comment by lokanchung** [comment]
No source is available because I literally editted the binary. You can diff mine with original firmware and see what's changed. It's just a few lines. Note that .bin is the binary and .syx is generated from it to send firmware to LPX via midi protocol.
